redis:
  image: redis
  container_name: cache
  expose:
    - 11939
app:
  build: ./
  volumes: 
    - ./:/usr/src/app
  ports: 
    - 3003:3003
  links:
    - redis
  environment: 
    - PORT=3003
    - REDIS_URL=redis://cache